"""Strict lock and receipt contracts for the packaging validation toolchain."""

from __future__ import annotations

import hashlib
import json
import os
import platform
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import NoReturn

LOCK_SCHEMA = "roundwright-validation-toolchain-lock/v1"
RECEIPT_SCHEMA = "roundwright-validation-toolchain-receipt/v1"
SUPPORTED_PLATFORMS = frozenset(
    {
        "windows-x86_64",
        "windows-aarch64",
        "macos-x86_64",
        "macos-aarch64",
        "linux-x86_64",
        "linux-aarch64",
    }
)
_DIGEST = re.compile(r"[0-9a-f]{64}\Z")
_VERSION = re.compile(r"[0-9]+(?:\.[0-9]+){1,3}\Z")


class ToolchainError(ValueError):
    """Raised when a toolchain lock, cache, or receipt fails closed."""


@dataclass(frozen=True)
class PlatformIdentity:
    system: str
    architecture: str
    python_implementation: str
    python_version: str

    @property
    def artifact_key(self) -> str:
        return f"{self.system}-{self.architecture}"

    @property
    def cache_key(self) -> str:
        return f"{self.artifact_key}-{self.python_implementation}-{self.python_version}"


@dataclass(frozen=True)
class UvArtifact:
    filename: str
    archive_format: str
    url: str
    sha256: str


@dataclass(frozen=True)
class ValidationToolchainLock:
    path: Path
    digest: str
    resolver_revision: int
    python_implementation: str
    python_version: str
    pip_version: str
    setuptools_version: str
    build_requirements: Path
    build_requirements_sha256: str
    pipx_version: str
    pipx_requirements: Path
    pipx_requirements_sha256: str
    uv_version: str
    uv_artifacts: dict[str, UvArtifact]

    @property
    def digest_hex(self) -> str:
        return self.digest.removeprefix("sha256:")


@dataclass(frozen=True)
class ResolvedToolchain:
    receipt: Path
    root: Path
    lock_digest: str
    platform: PlatformIdentity
    uv: Path
    managed_python: Path
    python: Path
    pipx: Path
    build_environment: Path
    pipx_environment: Path


def _fail(message: str) -> NoReturn:
    raise ToolchainError(message)


def _exact_mapping(value: object, keys: set[str], label: str) -> dict[str, object]:
    if type(value) is not dict or set(value) != keys:
        _fail(f"{label} fields are invalid")
    return value


def _string(value: object, label: str) -> str:
    if type(value) is not str or not value:
        _fail(f"{label} is invalid")
    return value


def _version(value: object, label: str) -> str:
    result = _string(value, label)
    if _VERSION.fullmatch(result) is None:
        _fail(f"{label} is invalid")
    return result


def _positive_integer(value: object, label: str) -> int:
    if type(value) is not int or value < 1:
        _fail(f"{label} is invalid")
    return value


def _sha256(value: object, label: str) -> str:
    result = _string(value, label)
    if _DIGEST.fullmatch(result) is None:
        _fail(f"{label} is invalid")
    return result


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _is_within(path: Path, boundary: Path) -> bool:
    def normalized(value: Path) -> str:
        result = os.path.normcase(os.path.abspath(value))
        if os.name == "nt" and result.startswith("\\\\?\\"):
            result = result[4:]
        return result

    target = normalized(path)
    allowed = normalized(boundary)
    try:
        return os.path.commonpath((target, allowed)) == allowed
    except ValueError:
        return False


def tree_sha256(path: Path, *, boundary: Path | None = None) -> str:
    """Hash a closed environment without interpreter-generated bytecode caches."""

    try:
        root = path.resolve(strict=True)
    except FileNotFoundError as error:
        raise ToolchainError("toolchain environment is unavailable") from error
    if not root.is_dir():
        _fail("toolchain environment is unavailable")
    allowed = root if boundary is None else boundary.resolve(strict=True)
    digest = hashlib.sha256()
    files = sorted(
        item for item in root.rglob("*") if item.is_file() and "__pycache__" not in item.parts and item.suffix != ".pyc"
    )
    if not files:
        _fail("toolchain environment is empty")
    for item in files:
        relative = item.relative_to(root).as_posix().encode("utf-8")
        target = item.resolve(strict=True)
        if not _is_within(target, allowed):
            raise ToolchainError("toolchain environment contains an escaping link")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(bytes.fromhex(file_sha256(target)))
    return digest.hexdigest()


def _repo_relative(root: Path, value: object, label: str) -> Path:
    raw = _string(value, label)
    pure = PurePosixPath(raw)
    if pure.is_absolute() or ".." in pure.parts or "." in pure.parts or "\\" in raw:
        _fail(f"{label} is invalid")
    try:
        path = (root / Path(*pure.parts)).resolve(strict=True)
        path.relative_to(root)
    except (FileNotFoundError, ValueError) as error:
        raise ToolchainError(f"{label} is unavailable") from error
    if not path.is_file():
        _fail(f"{label} is unavailable")
    return path


def load_lock(path: Path) -> ValidationToolchainLock:
    """Load a strict tracked lock and verify its referenced hashed inputs."""

    try:
        location = path.resolve(strict=True)
        raw = location.read_bytes()
        document = tomllib.loads(raw.decode("utf-8"))
    except (FileNotFoundError, OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ToolchainError("validation toolchain lock is unavailable") from error
    root = location.parents[1]
    top = _exact_mapping(document, {"schema", "contract", "python", "build", "pipx", "uv"}, "toolchain lock")
    if top["schema"] != LOCK_SCHEMA:
        _fail("toolchain lock schema is invalid")
    contract = _exact_mapping(top["contract"], {"resolver_revision", "receipt_schema"}, "toolchain contract")
    resolver_revision = _positive_integer(contract["resolver_revision"], "resolver revision")
    if contract["receipt_schema"] != RECEIPT_SCHEMA:
        _fail("receipt schema identity is invalid")

    python = _exact_mapping(top["python"], {"implementation", "version"}, "python lock")
    implementation = _string(python["implementation"], "python implementation")
    if implementation != "cpython":
        _fail("python implementation is unsupported")
    python_version = _version(python["version"], "python version")

    build = _exact_mapping(
        top["build"],
        {"pip_version", "setuptools_version", "requirements", "requirements_sha256"},
        "build lock",
    )
    build_requirements = _repo_relative(root, build["requirements"], "build requirements")
    build_requirements_sha256 = _sha256(build["requirements_sha256"], "build requirements digest")
    if file_sha256(build_requirements) != build_requirements_sha256:
        _fail("build requirements digest does not match")

    pipx = _exact_mapping(top["pipx"], {"version", "requirements", "requirements_sha256"}, "pipx lock")
    pipx_requirements = _repo_relative(root, pipx["requirements"], "pipx requirements")
    pipx_requirements_sha256 = _sha256(pipx["requirements_sha256"], "pipx requirements digest")
    if file_sha256(pipx_requirements) != pipx_requirements_sha256:
        _fail("pipx requirements digest does not match")

    uv = _exact_mapping(top["uv"], {"version", "artifacts"}, "uv lock")
    raw_artifacts = _exact_mapping(uv["artifacts"], set(SUPPORTED_PLATFORMS), "uv artifacts")
    artifacts: dict[str, UvArtifact] = {}
    for key, value in raw_artifacts.items():
        item = _exact_mapping(value, {"filename", "format", "url", "sha256"}, f"uv artifact {key}")
        archive_format = _string(item["format"], f"uv artifact {key} format")
        if archive_format not in {"zip", "tar.gz"}:
            _fail(f"uv artifact {key} format is unsupported")
        url = _string(item["url"], f"uv artifact {key} url")
        if not url.startswith("https://github.com/astral-sh/uv/releases/download/"):
            _fail(f"uv artifact {key} url is invalid")
        artifacts[key] = UvArtifact(
            filename=_string(item["filename"], f"uv artifact {key} filename"),
            archive_format=archive_format,
            url=url,
            sha256=_sha256(item["sha256"], f"uv artifact {key} digest"),
        )

    return ValidationToolchainLock(
        path=location,
        digest="sha256:" + hashlib.sha256(raw).hexdigest(),
        resolver_revision=resolver_revision,
        python_implementation=implementation,
        python_version=python_version,
        pip_version=_version(build["pip_version"], "pip version"),
        setuptools_version=_version(build["setuptools_version"], "setuptools version"),
        build_requirements=build_requirements,
        build_requirements_sha256=build_requirements_sha256,
        pipx_version=_version(pipx["version"], "pipx version"),
        pipx_requirements=pipx_requirements,
        pipx_requirements_sha256=pipx_requirements_sha256,
        uv_version=_version(uv["version"], "uv version"),
        uv_artifacts=artifacts,
    )


def current_platform(lock: ValidationToolchainLock) -> PlatformIdentity:
    systems = {"win32": "windows", "darwin": "macos", "linux": "linux"}
    machines = {"amd64": "x86_64", "x86_64": "x86_64", "arm64": "aarch64", "aarch64": "aarch64"}
    try:
        system = systems[sys.platform]
        architecture = machines[platform.machine().lower()]
    except KeyError as error:
        raise ToolchainError("host platform is unsupported") from error
    identity = PlatformIdentity(system, architecture, lock.python_implementation, lock.python_version)
    if identity.artifact_key not in lock.uv_artifacts:
        _fail("host platform is not present in the toolchain lock")
    return identity


def toolchain_root(cache_root: Path, lock: ValidationToolchainLock, identity: PlatformIdentity) -> Path:
    return cache_root.resolve() / lock.digest_hex / identity.cache_key


def _relative_tool(root: Path, path: Path, label: str) -> str:
    try:
        relative = path.relative_to(root)
    except ValueError as error:
        raise ToolchainError(f"{label} escapes the toolchain root") from error
    if not path.is_file():
        _fail(f"{label} is unavailable")
    return relative.as_posix()


def _tool_entry(root: Path, path: Path, version: str, label: str) -> dict[str, str]:
    relative = _relative_tool(root, path, label)
    target = path.resolve(strict=True)
    try:
        target.relative_to(root.resolve(strict=True))
    except ValueError as error:
        raise ToolchainError(f"{label} escapes the toolchain root") from error
    return {"path": relative, "version": version, "sha256": file_sha256(target)}


def _canonical_receipt(document: dict[str, object]) -> bytes:
    payload = {key: value for key, value in document.items() if key != "receipt_digest"}
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii")


def create_receipt(
    root: Path,
    lock: ValidationToolchainLock,
    identity: PlatformIdentity,
    *,
    uv: Path,
    managed_python: Path,
    python: Path,
    pipx: Path,
    managed_python_environment: Path,
    build_environment: Path,
    pipx_environment: Path,
) -> dict[str, object]:
    document: dict[str, object] = {
        "schema": RECEIPT_SCHEMA,
        "lock_digest": lock.digest,
        "platform": {
            "system": identity.system,
            "architecture": identity.architecture,
            "python_implementation": identity.python_implementation,
            "python_version": identity.python_version,
        },
        "requirements": {
            "build": "sha256:" + lock.build_requirements_sha256,
            "pipx": "sha256:" + lock.pipx_requirements_sha256,
        },
        "environments": {
            "python": {
                "path": managed_python_environment.relative_to(root).as_posix(),
                "sha256": tree_sha256(managed_python_environment, boundary=root),
            },
            "build": {
                "path": build_environment.relative_to(root).as_posix(),
                "sha256": tree_sha256(build_environment, boundary=root),
            },
            "pipx": {
                "path": pipx_environment.relative_to(root).as_posix(),
                "sha256": tree_sha256(pipx_environment, boundary=root),
            },
        },
        "tools": {
            "uv": _tool_entry(root, uv, lock.uv_version, "uv executable"),
            "managed_python": _tool_entry(root, managed_python, lock.python_version, "managed Python executable"),
            "python": _tool_entry(root, python, lock.python_version, "validation Python executable"),
            "pipx": _tool_entry(root, pipx, lock.pipx_version, "pipx executable"),
        },
    }
    document["receipt_digest"] = "sha256:" + hashlib.sha256(_canonical_receipt(document)).hexdigest()
    return document


def _reject_constant(value: str) -> NoReturn:
    raise ToolchainError(f"receipt contains invalid constant {value}")


def _reject_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            _fail("receipt contains duplicate fields")
        result[key] = value
    return result


def _receipt_tool(root: Path, value: object, expected_version: str, label: str) -> Path:
    item = _exact_mapping(value, {"path", "version", "sha256"}, label)
    if item["version"] != expected_version:
        _fail(f"{label} version is stale")
    relative = PurePosixPath(_string(item["path"], f"{label} path"))
    if relative.is_absolute() or ".." in relative.parts or "." in relative.parts:
        _fail(f"{label} path is invalid")
    try:
        command = (root / Path(*relative.parts)).resolve(strict=True)
        command.relative_to(root.resolve(strict=True))
    except (FileNotFoundError, ValueError) as error:
        raise ToolchainError(f"{label} is unavailable") from error
    if not command.is_file() or file_sha256(command) != _sha256(item["sha256"], f"{label} digest"):
        _fail(f"{label} digest does not match")
    return command


def _receipt_environment(root: Path, value: object, label: str) -> Path:
    item = _exact_mapping(value, {"path", "sha256"}, label)
    relative = PurePosixPath(_string(item["path"], f"{label} path"))
    if relative.is_absolute() or ".." in relative.parts or "." in relative.parts:
        _fail(f"{label} path is invalid")
    try:
        environment = (root / Path(*relative.parts)).resolve(strict=True)
        environment.relative_to(root.resolve(strict=True))
    except (FileNotFoundError, ValueError) as error:
        raise ToolchainError(f"{label} is unavailable") from error
    if tree_sha256(environment, boundary=root) != _sha256(item["sha256"], f"{label} digest"):
        _fail(f"{label} digest does not match")
    return environment


def _read_back(command: list[str], label: str) -> str:
    environment = os.environ.copy()
    environment.pop("PYTHONPATH", None)
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    result = subprocess.run(command, env=environment, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        _fail(f"{label} read-back failed")
    return result.stdout.strip()


def verify_receipt(
    path: Path,
    lock: ValidationToolchainLock,
    identity: PlatformIdentity,
    *,
    read_back: bool = True,
) -> ResolvedToolchain:
    """Verify an exact receipt, its layout, every executable hash, and versions."""

    try:
        location = path.resolve(strict=True)
        document = json.loads(
            location.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicates,
            parse_constant=_reject_constant,
        )
    except (FileNotFoundError, OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ToolchainError("validation toolchain receipt is unavailable") from error
    if location.name != "receipt.json" or location.parent.name != identity.cache_key or location.parent.parent.name != lock.digest_hex:
        _fail("validation toolchain receipt location is stale")
    top = _exact_mapping(
        document,
        {"schema", "lock_digest", "platform", "requirements", "environments", "tools", "receipt_digest"},
        "toolchain receipt",
    )
    if top["schema"] != RECEIPT_SCHEMA or top["lock_digest"] != lock.digest:
        _fail("validation toolchain receipt is stale")
    expected_receipt_digest = "sha256:" + hashlib.sha256(_canonical_receipt(top)).hexdigest()
    if top["receipt_digest"] != expected_receipt_digest:
        _fail("validation toolchain receipt digest does not match")

    observed_platform = _exact_mapping(
        top["platform"],
        {"system", "architecture", "python_implementation", "python_version"},
        "receipt platform",
    )
    if observed_platform != {
        "system": identity.system,
        "architecture": identity.architecture,
        "python_implementation": identity.python_implementation,
        "python_version": identity.python_version,
    }:
        _fail("validation toolchain receipt platform is stale")
    requirements = _exact_mapping(top["requirements"], {"build", "pipx"}, "receipt requirements")
    if requirements != {
        "build": "sha256:" + lock.build_requirements_sha256,
        "pipx": "sha256:" + lock.pipx_requirements_sha256,
    }:
        _fail("validation toolchain receipt requirements are stale")

    tools = _exact_mapping(top["tools"], {"uv", "managed_python", "python", "pipx"}, "receipt tools")
    root = location.parent
    environments = _exact_mapping(top["environments"], {"python", "build", "pipx"}, "receipt environments")
    _receipt_environment(root, environments["python"], "managed Python environment")
    build_environment = _receipt_environment(root, environments["build"], "build environment")
    pipx_environment = _receipt_environment(root, environments["pipx"], "pipx environment")
    uv = _receipt_tool(root, tools["uv"], lock.uv_version, "uv executable")
    managed_python = _receipt_tool(root, tools["managed_python"], lock.python_version, "managed Python executable")
    python = _receipt_tool(root, tools["python"], lock.python_version, "validation Python executable")
    pipx = _receipt_tool(root, tools["pipx"], lock.pipx_version, "pipx executable")

    if read_back:
        if _read_back([str(uv), "--version"], "uv").split()[:2] != ["uv", lock.uv_version]:
            _fail("uv read-back version is stale")
        python_probe = "import platform; print(platform.python_implementation(), platform.python_version())"
        expected_python = f"CPython {lock.python_version}"
        for command, label in ((managed_python, "managed Python"), (python, "validation Python")):
            if _read_back([str(command), "-I", "-c", python_probe], label) != expected_python:
                _fail(f"{label} read-back version is stale")
        if _read_back([str(pipx), "--version"], "pipx") != lock.pipx_version:
            _fail("pipx read-back version is stale")
        build_probe = "import pip, setuptools; print(pip.__version__, setuptools.__version__)"
        if _read_back([str(python), "-I", "-c", build_probe], "build tools") != f"{lock.pip_version} {lock.setuptools_version}":
            _fail("build tool read-back version is stale")

    return ResolvedToolchain(
        location,
        root,
        lock.digest,
        identity,
        uv,
        managed_python,
        python,
        pipx,
        build_environment,
        pipx_environment,
    )
